"""Documented evidence and concrete repairs for hookprobe findings."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Evidence:
    """The reason a finding matters and the concrete way to repair it."""

    code: str
    title: str
    severity: str
    explanation: str
    repair: str
    references: tuple[str, ...]


def _e(
    code: str,
    title: str,
    severity: str,
    explanation: str,
    repair: str,
    *references: str,
) -> Evidence:
    return Evidence(code, title, severity, explanation, repair, tuple(references))


EVIDENCE: dict[str, Evidence] = {
    entry.code: entry
    for entry in (
        _e(
            "P08.BLOCKS_EVERYTHING",
            "Handler rejects the neutral payload too",
            "warning",
            "The handler exits 2 even for an ordinary tool call, so it does not filter -- it blocks the event outright. That is a valid choice for a kill switch and a mistake everywhere else.",
            "Narrow the rejection condition, or confirm on purpose that this event should always be blocked.",
            "docs:decision-control",
        ),
        _e(
            "P09.PLAIN_TEXT",
            "Plain-text output is used as context",
            "info",
            "For UserPromptSubmit, UserPromptExpansion, SessionStart and PostModelSwitch, Claude Code adds plain stdout to the context Claude can see. JSON is only needed for structured control.",
            "Nothing to repair unless the handler meant to steer a decision, which requires JSON.",
            "docs:json-parsing",
        ),
        _e(
            "P01.MISSING_FILE",
            "Hook file is missing",
            "critical",
            'The command cannot start. The documentation warns that "a mistyped path in settings.json leaves the gate silently disabled"; the shell exits 127 and the protected action proceeds.',
            "Restore the file or correct the command to an existing absolute path.",
            "anthropics/claude-code#32990",
            "docs:hook-cannot-start",
        ),
        _e(
            "P01.NOT_EXECUTABLE",
            "Hook file is not executable",
            "critical",
            "A directly invoked script without the current user's execute bit never reaches its policy logic, so Claude Code treats the launch failure as non-blocking.",
            "Run chmod +x <path> and preserve the executable bit in version control and packaging.",
            "anthropics/claude-code#94362",
            "docs:hook-cannot-start",
        ),
        _e(
            "P01.NO_SHEBANG",
            "Direct script has no shebang",
            "critical",
            "An executable text file invoked directly needs a shebang naming its interpreter; otherwise the operating system cannot start it reliably.",
            "Add a valid shebang as the first line or invoke the script through an explicit interpreter.",
            "docs:exec-form",
        ),
        _e(
            "P01.MISSING_INTERPRETER",
            "Interpreter is unavailable",
            "critical",
            "A wrapper or shebang interpreter that is absent from PATH prevents the hook from starting. A Microsoft Store Python stub can instead exit 49, with the same fail-open result.",
            "Install the interpreter, put the real executable on PATH, or use an existing absolute interpreter path.",
            "anthropics/claude-code#90077",
            "anthropics/claude-code#57946",
            "docs:exec-form",
        ),
        _e(
            "P01.UNQUOTED_PLACEHOLDER",
            "Path placeholder is unquoted",
            "critical",
            "In shell form, an expanded project or plugin path containing spaces is word-split before the hook script can run. One reported session silently skipped 6,865 guards this way.",
            'Switch to exec form with "args", or wrap every path placeholder in double quotes.',
            "anthropics/claude-code#81458",
            "anthropics/claude-code#78490",
            "docs:path-placeholders",
        ),
        _e(
            "P01.UNSET_PLACEHOLDER",
            "Path placeholder has no value",
            "critical",
            "Plugin-only placeholders have no defined value outside a plugin hook, so substitution cannot produce the intended command path.",
            "Move the hook into the plugin source or replace the plugin placeholder with a valid project-relative exec-form argument.",
            "docs:path-placeholders",
        ),
        _e(
            "P01.SPACE_IN_PATH",
            "Shell path with spaces is unquoted",
            "critical",
            "The shell word-splits an unquoted path and attempts to execute its first segment, commonly exiting 127 before the hook runs.",
            "Quote the complete path or use exec form with a separate args list.",
            "anthropics/claude-code#39478",
            "docs:exec-form",
        ),
        _e(
            "P01.BACKSLASH_PATH",
            "Shell command contains backslashes",
            "warning",
            "Git Bash can consume Windows path backslashes as escapes, changing the executable path and silently preventing the hook from running.",
            "Use forward slashes, exec form, or a PowerShell command with native path syntax.",
            "anthropics/claude-code#88578",
            "docs:windows-powershell",
        ),
        _e(
            "P01.SH_WITHOUT_INTERPRETER",
            "Shell script is invoked directly on Windows",
            "critical",
            "Windows does not execute a Unix shebang directly; a bare .sh association can open a console window without enforcing the hook.",
            'Invoke the script as "bash <path>" or use exec form with bash as command and the script in args.',
            "anthropics/claude-code#95673",
            "docs:exec-form",
        ),
        _e(
            "P01.RELATIVE_PATH",
            "Hook path depends on working directory",
            "warning",
            "Claude Code may fall back to the session start directory, project root, home, or temp when the current directory disappears, making a relative script path resolve somewhere else.",
            "Use ${CLAUDE_PROJECT_DIR} in exec form to make the script path independent of cwd.",
            "anthropics/claude-code#67147",
            "docs:path-placeholders",
        ),
        _e(
            "P01.SPAWN_FAILED",
            "Hook launch failed during probe",
            "critical",
            'The observed launch result shows that the hook never reached its logic. The documentation says that for most events "the action proceeds" when a hook cannot start.',
            "Fix the reported executable, interpreter, path, or permission error and rerun the probe.",
            "docs:hook-cannot-start",
        ),
        _e(
            "P01.PLUGIN_PERMISSIONS",
            "Plugin script lost its executable bit",
            "critical",
            "Plugin installation has been observed to materialize shell scripts as mode 0644 instead of 0755, leaving directly invoked hooks inert.",
            "Preserve executable metadata in the plugin package and run chmod +x on the installed script.",
            "anthropics/claude-code#20432",
        ),
        _e(
            "P01.NOT_TESTED",
            "Handler was not executed offline",
            "info",
            "HTTP and MCP handlers need external services, while prompt and agent handlers need a model; the offline probe cannot execute them without changing its safety and cost contract.",
            "Use the live verification mode in an authorized environment, or test the external handler independently.",
            "docs:hook-handler-fields",
        ),
        _e(
            "P02.DENY_NOT_ENFORCED",
            "Deny decision was not enforced",
            "critical",
            "A real tool call completed despite a deny result, so the declared policy did not protect that source or execution channel.",
            "Move enforcement to a verified source/channel or upgrade past the affected runtime and repeat the live canary.",
            "anthropics/claude-code#94362",
            "anthropics/claude-code#90564",
            "anthropics/claude-code#84701",
            "anthropics/claude-code#92675",
            "anthropics/claude-code#33343",
        ),
        _e(
            "P02.ENFORCED",
            "Deny decision was enforced",
            "info",
            "The live canary did not execute while its control did, which is direct evidence that this hook affected the tested tool call.",
            "Keep the hook executable and rerun the canary after configuration or runtime changes.",
            "docs:pretooluse-decision-control",
        ),
        _e(
            "P02.INCONCLUSIVE",
            "Live control was inconclusive",
            "warning",
            "The control run did not produce the expected side effect, so absence of the side effect in the hooked run proves nothing about enforcement.",
            "Fix the control command or environment, then repeat both control and hooked runs.",
            "docs:pretooluse-decision-control",
        ),
        _e(
            "P03.UNKNOWN_EVENT",
            "Unknown hook event",
            "critical",
            "One schema-invalid entry has been observed to disable every hook in its settings file, leaving roughly 100 hooks inactive for 30 hours.",
            "Replace the event with a documented event name and validate the complete settings file.",
            "anthropics/claude-code#75071",
            "docs:hook-events",
        ),
        _e(
            "P03.BAD_MATCHER_TYPE",
            "Matcher is not a string",
            "critical",
            "A schema-invalid matcher can prevent the containing settings file's hooks from loading at all.",
            "Replace the matcher with a string, or omit it to match every event occurrence.",
            "anthropics/claude-code#75071",
            "docs:matcher-patterns",
        ),
        _e(
            "P03.BAD_GROUP",
            "Hook group has an invalid shape",
            "critical",
            "A malformed matcher group can invalidate hook loading for the settings file rather than only skipping that group.",
            "Make the event value a list of objects, each with a list-valued hooks field.",
            "anthropics/claude-code#75071",
            "docs:configuration",
        ),
        _e(
            "P03.BAD_HANDLER_TYPE",
            "Handler type is invalid",
            "critical",
            "An unknown or missing handler type cannot be dispatched and can make the hook configuration schema-invalid.",
            "Set type to command, http, mcp_tool, prompt, or agent as supported by the event.",
            "anthropics/claude-code#75071",
            "docs:hook-handler-fields",
        ),
        _e(
            "P03.MISSING_COMMAND",
            "Command handler has no command",
            "critical",
            "A command handler without an executable or shell command cannot start and is schema-invalid.",
            "Add a non-empty command field, using args for exec form where appropriate.",
            "anthropics/claude-code#75071",
            "docs:command-hook-fields",
        ),
        _e(
            "P03.SANDBOX_NON_STRING",
            "Sandbox deny entry is not a string",
            "critical",
            "A non-string denyRead or denyWrite entry has been observed to disable permission enforcement and prevent PreToolUse dispatch.",
            "Replace every sandbox.filesystem denyRead and denyWrite item with a path string.",
            "anthropics/claude-code#92365",
        ),
        _e(
            "P03.HOOKS_DISABLED",
            "All hooks are disabled",
            "critical",
            'The effective setting "disableAllHooks": true prevents configured hooks from running.',
            "Remove disableAllHooks or set it to false at the settings level that controls these hooks.",
            "docs:disable-hooks",
        ),
        _e(
            "P04.MATCHER_IGNORED",
            "Matcher is silently ignored",
            "warning",
            'The documentation states: "If you add a matcher field to an event without matcher support, it is silently ignored." The hook runs more broadly than intended.',
            "Remove the matcher and make the handler safely process every occurrence of the event.",
            "docs:matcher-patterns",
        ),
        _e(
            "P04.IF_ON_NON_TOOL_EVENT",
            "if filter prevents the hook from running",
            "critical",
            'The if field is only evaluated on tool events; the documentation says that on other events "a hook with if set never runs."',
            "Remove if or move the condition into the hook program for this event.",
            "docs:common-fields",
        ),
        _e(
            "P04.IF_BEST_EFFORT",
            "if filter is best effort",
            "info",
            'The documentation warns: "Because the if filter is best-effort, use the permission system rather than a hook to enforce a hard allow or deny."',
            "Move hard enforcement to permission rules and treat if only as an optimization.",
            "anthropics/claude-code#95819",
            "anthropics/claude-code#84632",
            "docs:if-best-effort",
        ),
        _e(
            "P04.EXACT_NO_MATCH",
            "Exact matcher names no available tool",
            "critical",
            "Tool names are case-sensitive, and an incomplete MCP prefix such as mcp__memory matches no tool without a pattern such as .*, so the hook never fires.",
            "Use an exact documented tool name or an anchored MCP matcher such as ^mcp__memory__.*$.",
            "anthropics/claude-code#33585",
            "anthropics/claude-code#74942",
            "docs:matcher-patterns",
        ),
        _e(
            "P04.UNANCHORED_REGEX",
            "Regular expression matches too broadly",
            "warning",
            'JavaScript matcher tests are unanchored; the documentation notes that "Edit.* matches both Edit and NotebookEdit."',
            "Add ^ and $ anchors when the matcher is intended to cover a whole value.",
            "docs:matcher-patterns",
        ),
        _e(
            "P04.BAD_REGEX",
            "Matcher regular expression is invalid",
            "critical",
            "An invalid matcher cannot select the event values the hook is intended to protect.",
            "Correct the regular expression and test it against the documented matched field.",
            "docs:matcher-patterns",
        ),
        _e(
            "P04.UNKNOWN_MATCHER_VALUE",
            "Matcher names an undocumented value",
            "critical",
            "An exact matcher value outside the documented event values never selects a real occurrence.",
            "Replace it with one of the documented values for this event.",
            "docs:matcher-patterns",
        ),
        _e(
            "P04.NARROW_EXACT_SET",
            "Matcher uses the wrong exact-set syntax",
            "warning",
            "FileChanged and StopFailure only split exact alternatives on |; a comma sends the matcher down the regular-expression path instead.",
            "Replace commas with | for FileChanged and StopFailure alternatives.",
            "docs:matcher-patterns",
        ),
        _e(
            "P04.MATCH_NOT_CONSTRUCTED",
            "Probe could not construct a matching value",
            "info",
            "The matcher is an open regular expression for which hookprobe has no safe documented sample, so the synthetic run may not exercise the same branch as Claude Code.",
            "Run the hook with a representative captured payload or narrow the matcher to documented exact values.",
            "docs:matcher-patterns",
        ),
        _e(
            "P05.AGENT_FRONTMATTER",
            "Agent-frontmatter hook may not fire",
            "critical",
            "Identical PreToolUse hooks have been observed to fire from settings.json but remain silent from agent frontmatter.",
            "Move the hook to settings.json and scope it by the agent_type input field.",
            "anthropics/claude-code#95650",
            "anthropics/claude-code#39468",
        ),
        _e(
            "P05.SKILL_ONCE",
            "Skill once hook may repeat",
            "warning",
            "A skill-frontmatter hook with once: true has been observed running on every later matching call instead of being removed.",
            "Make the handler idempotent and persist your own one-shot marker if repetition is unsafe.",
            "anthropics/claude-code#95280",
        ),
        _e(
            "P05.ONCE_IGNORED",
            "once is ignored at this source",
            "warning",
            'The documentation says once is "ignored in settings files and agent frontmatter," so the handler remains registered.',
            "Remove once and implement idempotence or move a genuinely one-shot hook to skill frontmatter.",
            "docs:common-fields",
        ),
        _e(
            "P05.PLUGIN_SOURCE",
            "Plugin-sourced enforcement needs verification",
            "info",
            "Plugin-native enforcement and plugin executable permissions have both shown source-specific failures.",
            "Run live verification for the plugin source and preserve executable modes in its package.",
            "anthropics/claude-code#92675",
            "anthropics/claude-code#20432",
        ),
        _e(
            "P06.CHANNEL_DIVERGENCE",
            "Hook behavior differs by channel",
            "critical",
            'The documentation promises that Claude Code "fires the same hook events wherever it runs," but reported headless, Desktop, VS Code, and background behavior diverges.',
            "Use only channels that pass the live canary, and retest after upgrading Claude Code.",
            "anthropics/claude-code#95726",
            "anthropics/claude-code#95833",
            "anthropics/claude-code#92074",
            "anthropics/claude-code#88698",
            "docs:hook-lifecycle",
        ),
        _e(
            "P07.OVER_CAP",
            "Hook output exceeds the context cap",
            "critical",
            'For values over 10,000 characters, "Claude Code doesn\'t ask Claude to read the file" containing the remainder, so policy or context after the preview may never reach the model.',
            "Reduce each emitted context field below 10,000 characters and put essential material in the first 2,000.",
            "anthropics/claude-code#94358",
            "anthropics/claude-code#84021",
            "anthropics/claude-code#70460",
            "docs:output-cap",
        ),
        _e(
            "P07.NEAR_CAP",
            "Hook output is near the context cap",
            "warning",
            "The output is close to the fixed 10,000-character ceiling, so modest growth can replace most of it with only a 2,000-character preview.",
            "Shorten the field or split nonessential material out before it reaches the cap.",
            "docs:output-cap",
        ),
        _e(
            "P08.EXIT_ONE_ON_REJECT",
            "Reject path uses a non-blocking exit code",
            "critical",
            'The documentation warns: "Claude Code treats exit code 1 as a non-blocking error and proceeds with the action." Other nonzero codes except 2 behave the same for most events.',
            "Return exit code 2 on every rejection path, or emit the event's valid blocking JSON decision with exit 0.",
            "docs:exit-code-2",
        ),
        _e(
            "P08.NO_BLOCK_OBSERVED",
            "Probe observed no blocking result",
            "warning",
            "The supplied deny probe produced neither exit 2 nor an event-appropriate blocking JSON decision. This only describes the tested payload, not every possible input.",
            "Test the intended rejection payload and make its rejection path return exit 2 or valid blocking JSON.",
            "docs:decision-control",
        ),
        _e(
            "P08.EXIT_TWO_ON_NON_BLOCKING",
            "Exit 2 cannot block this event",
            "warning",
            "Some events represent actions that already happened or explicitly ignore exit 2, so a blocking-looking exit cannot enforce policy there.",
            "Move the policy to a pre-action blocking event or use the event-specific decision object where one exists.",
            "anthropics/claude-code#46468",
            "docs:exit-code-2-per-event",
        ),
        _e(
            "P08.SET_E_WITHOUT_TRAP",
            "set -e can produce a non-blocking failure",
            "warning",
            "Without a trap, a failing helper terminates a shell hook with the helper's status, which is usually 1 rather than the blocking code 2.",
            "Add an error trap that maps policy failure to exit 2 and operational failure to an explicit safe outcome.",
            "docs:exit-code-2",
        ),
        _e(
            "P08.BLOCKED_AS_EXPECTED",
            "Probe observed a blocking result",
            "info",
            "The deny payload produced exit 2 or an event-appropriate blocking decision, so this handler can block the tested synthetic call.",
            "Keep a regression probe for this payload and verify end-to-end enforcement with live mode.",
            "docs:decision-control",
        ),
        _e(
            "P09.PREAMBLE",
            "Text appears before JSON",
            "critical",
            'The documentation requires that "stdout must contain only the JSON object"; a profile banner makes the whole response plain text and the decision is not parsed.',
            "Suppress shell profile output and write only one JSON object to stdout.",
            "docs:json-output",
        ),
        _e(
            "P09.UNTERMINATED_OBJECT",
            "JSON-looking output is treated as text",
            "critical",
            'The documented parser rule says output that "starts with { but doesn\'t end with }" is treated as plain text, silently discarding a decision.',
            "Emit one complete JSON object with no trailing non-whitespace text.",
            "docs:json-parsing",
        ),
        _e(
            "P09.NOT_JSON",
            "JSON output cannot be parsed",
            "critical",
            "A JSON-looking response that does not parse becomes a non-blocking hook error on standard decision events, so the action proceeds.",
            "Serialize the response with a JSON library and emit no other stdout.",
            "docs:json-parsing",
        ),
        _e(
            "P09.MULTIPLE_OBJECTS",
            "Hook emitted multiple JSON objects",
            "critical",
            "Claude Code applies a special multi-line rule rather than merging JSON lines; decision-bearing lines can turn the whole response into a parse failure.",
            "Combine all fields into one JSON object and print it once.",
            "docs:json-parsing",
        ),
        _e(
            "P09.WRONG_DECISION_FIELD",
            "Decision field belongs to another event",
            "critical",
            "PreToolUse, PermissionRequest, and standard-decision events read different JSON paths; a valid decision in the wrong path has no blocking effect.",
            "Use hookSpecificOutput.permissionDecision for PreToolUse, hookSpecificOutput.decision.behavior for PermissionRequest, or top-level decision for standard events.",
            "anthropics/claude-code#90014",
            "docs:decision-control",
        ),
        _e(
            "P09.UNKNOWN_DECISION_VALUE",
            "Decision value is unsupported",
            "critical",
            "An unsupported decision value fails schema validation or has no defined enforcement behavior, so it cannot be relied on to block.",
            "Use only the documented decision values for this event.",
            "anthropics/claude-code#90014",
            "docs:decision-control",
        ),
        _e(
            "P10.STDIN_BLOCK",
            "Hook does not finish after stdin closes",
            "critical",
            "The empty-stdin probe found a process that remains blocked or spinning after end-of-file; reported hooks have exceeded a declared 3-second timeout by more than 300 seconds.",
            "Make stdin reads terminate at EOF and add an internal timeout around any other blocking operation.",
            "anthropics/claude-code#87289",
            "anthropics/claude-code#86578",
            "anthropics/claude-code#90585",
        ),
        _e(
            "P10.PROBE_TIMEOUT",
            "Probe stopped a long-running hook",
            "warning",
            "hookprobe uses a short safety timeout rather than waiting for Claude Code's much longer default, so this finding records a probe cutoff rather than the harness timer itself.",
            "Run the hook directly with a controlled longer limit to distinguish slow work from a permanent stall.",
            "docs:timeouts",
        ),
        _e(
            "P10.SLOW",
            "Hook consumes most of its timeout budget",
            "warning",
            "A hook using more than half its effective budget has little headroom for slower machines or transient load and may lose its decision at timeout.",
            "Reduce the work on the synchronous path or raise the declared timeout within acceptable latency bounds.",
            "docs:timeouts",
        ),
        _e(
            "P10.NO_TIMEOUT_FIELD",
            "Hook relies on the default timeout",
            "info",
            "Without a timeout field, Claude Code applies the event and handler-type default, which may be much longer than intended for a policy gate.",
            "Set an explicit timeout appropriate for the handler's expected runtime.",
            "docs:timeouts",
        ),
        _e(
            "P10.TIMED_OUT_DOES_NOT_BLOCK",
            "Timed-out hook fails open",
            "critical",
            'For a timed-out command hook, the documentation warns: "don\'t count on a stalled hook to act as a gate." The protected action normally continues.',
            "Make the hook finish well within its timeout and enforce a safe internal failure path.",
            "docs:timeouts",
        ),
        _e(
            "CONFIG.UNREADABLE",
            "Configuration could not be read",
            "critical",
            "Unreadable hook configuration cannot contribute any handlers to the effective setup.",
            "Restore read permission and valid text encoding, then reload the configuration.",
            "docs:hook-locations",
        ),
        _e(
            "CONFIG.BAD_JSON",
            "Configuration JSON is invalid",
            "critical",
            "Invalid JSON prevents the settings file from being parsed and its hooks from loading.",
            "Correct the reported JSON syntax or root type.",
            "docs:configuration",
        ),
        _e(
            "CONFIG.FRONTMATTER_UNPARSED",
            "Hook frontmatter could not be parsed",
            "critical",
            "Unparsed skill or agent frontmatter means its hooks are absent from the loaded configuration.",
            "Rewrite the frontmatter as supported YAML with a mapping-valued hooks section.",
            "docs:hooks-in-skills-and-agents",
        ),
        _e(
            "CONFIG.NO_HOOKS",
            "No hooks were discovered",
            "warning",
            "With no discovered hook entries, hookprobe has no configured protection to exercise.",
            "Point hookprobe at the intended project or pass the correct settings files.",
            "docs:hook-locations",
        ),
        _e(
            "CONFIG.BAD_MATCHER_TYPE",
            "Configuration matcher is not a string",
            "critical",
            "The loader found a matcher with an invalid schema type.",
            "Replace the matcher with a string.",
            "anthropics/claude-code#75071",
            "docs:matcher-patterns",
        ),
        _e(
            "CONFIG.BAD_GROUP",
            "Configuration hook group is invalid",
            "critical",
            "The loader could not interpret the event's matcher-group structure.",
            "Use a list of matcher-group objects with list-valued hooks fields.",
            "anthropics/claude-code#75071",
            "docs:configuration",
        ),
        _e(
            "CONFIG.BAD_HANDLER_TYPE",
            "Configuration handler type is invalid",
            "critical",
            "The loader found a handler it cannot dispatch.",
            "Choose a documented handler type supported by the event.",
            "docs:hook-handler-fields",
        ),
        _e(
            "CONFIG.MISSING_COMMAND",
            "Configuration command is missing",
            "critical",
            "A command handler without a command cannot be executed.",
            "Add a command field to the handler.",
            "docs:command-hook-fields",
        ),
        _e(
            "CONFIG.UNKNOWN_EVENT",
            "Configuration event is unknown",
            "critical",
            "An unknown event is schema-invalid and can keep other hooks in the file from loading.",
            "Replace it with a documented hook event name.",
            "anthropics/claude-code#75071",
            "docs:hook-events",
        ),
        _e(
            "CONFIG.SANDBOX_NON_STRING",
            "Configuration sandbox path is not a string",
            "critical",
            "A non-string sandbox path has been observed disabling permission enforcement.",
            "Replace it with a path string.",
            "anthropics/claude-code#92365",
        ),
        _e(
            "CONFIG.BAD_DISABLE_ALL_HOOKS",
            "disableAllHooks has the wrong type",
            "warning",
            "A non-boolean disableAllHooks value is invalid and makes the effective disable state ambiguous.",
            "Set disableAllHooks to true or false.",
            "docs:disable-hooks",
        ),
    )
}


def lookup(code: str) -> Evidence:
    """Return evidence for code, falling back to a stable generic entry."""

    return EVIDENCE.get(
        code,
        Evidence(
            code=code,
            title="Uncatalogued finding",
            severity="info",
            explanation="No specific evidence entry is available for this finding code.",
            repair="Review the finding details and the current Claude Code hooks documentation.",
            references=(),
        ),
    )


def references_for(code: str) -> tuple[str, ...]:
    """Return the reference identifiers associated with code."""

    return lookup(code).references


def all_codes() -> list[str]:
    """Return every catalogued finding code in deterministic order."""

    return sorted(EVIDENCE)
